version: '3'

services:
  db:
    image: mariadb:10.5
    container_name: sam_maria
    environment:
      MYSQL_ROOT_PASSWORD: sam_db
      MYSQL_DATABASE: sam_db
      MYSQL_USER: sam_db
      MYSQL_PASSWORD: sam_db_db
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  php_my_admin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: sam_pma
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

